name: Hello World
on: #[push, pull_request]
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]

  repository_dispatch:
    types: ["on-demand-test"]
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello GitHub Actions!"
  Second-job:
    runs-on: windows-latest
    needs: hello-job
    steps:
      - run: echo "This job is running on ${{runner.os}}"
