name: Hello World
env:
  APP_NAME: "Demo Application"
on: #[push, pull_request]
  push:
    branches: [ main ]
    #paths-ignore:
      #- ".github/workflows/*"
  pull_request:
    branches: [ main ]

  repository_dispatch:
    types: ["on-demand-test"]
    
jobs:
  echo-vars:
    env:
      PACKAGE_PATH: "."
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub variable
        env:
          APP_VERSION: "1.0.0"
          RUNNER_CONTEXT: ${{ toJSON(runn) }}
        run: |
          echo "This job trigger by ${{ github.event_name }} event";
          echo "Repository is ${{ github.repository }}";
          echo "Branch is ${{ github.ref_name }}";
          echo "This is a ${{ env.APP_NAME }} version ${{ env.APP_VERSION }}";
          echo "Runner context: ${{ env.RUNNER_CONTEXT }}";
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello GitHub Actions!"
      - name: Retrieve client payload
        run: |
          echo "Client payload: ${{ github.event.client_payload.status }}"

  Second-job:
    runs-on: windows-latest
    needs: hello-job
    steps:    
      - run: echo "This job is running on ${{runner.os}}"