name: Hello World
on: #[push, pull_request]
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]

  repository_dispatch:
    #types: [workflow_dispatch]
    types: [workflow_dispatch]
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout repository
      #  uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello GitHub Actions!"